import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { FavoritesProvider } from "./components/FavoritesContext";
import { CartProvider } from "./components/CartContext";
import { ReservasProvider } from "./components/ReservasContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}>

        {/* Contenedor para imágenes que vuelan */}
        <div
          id="flying-image-container"
          className="pointer-events-none fixed top-0 left-0 w-full h-full"
        ></div>

        <FavoritesProvider>
          <CartProvider>
            <ReservasProvider>
              {children}
            </ReservasProvider>
          </CartProvider>
        </FavoritesProvider>

      </body>
    </html>
  );
}
